version: '3.7'
networks:
  ribacnet:
    external: false

services:
  ribac-db:
    image: mysql:8.0
    ports:
    - ${RIBAC_DB_EXTERNAL_PORT:?RIBAC_DB_EXTERNAL_PORT}:3306
    restart: always
    networks:
    - ribacnet
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${RIBAC_DB_ROOT_PASSWORD:?RIBAC_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${RIBAC_DB_NAME:?RIBAC_DB_NAME}
      MYSQL_USER: ${RIBAC_DB_USER:?RIBAC_DB_USER}
      MYSQL_PASSWORD: ${RIBAC_DB_PASSWORD:?RIBAC_DB_PASSWORD}
    volumes:
    - ./ribac.sql:/docker-entrypoint-initdb.d/ribac.sql:ro

  ribac:
    image: jonastauliensolutions/ribac:${RIBAC_VERSION:?RIBAC_VERSION}
    networks:
    - ribacnet
    depends_on:
    - ribac-db
    ports:
    - ${RIBAC_EXTERNAL_PORT:?RIBAC_EXTERNAL_PORT}:8080
    - ${RIBAC_EXTERNAL_DEBUG_PORT:?RIBAC_EXTERNAL_DEBUG_PORT}:5005
    restart: always
    environment:
      RIBAC_DB_HOST: ribac-db
      RIBAC_DB_PORT: 3306
      RIBAC_DB_NAME: ${RIBAC_DB_NAME:?RIBAC_DB_NAME}
      RIBAC_DB_USER: ${RIBAC_DB_USER:?RIBAC_DB_USER}
      RIBAC_DB_PASSWORD: ${RIBAC_DB_PASSWORD:?RIBAC_DB_PASSWORD}

  ribac-swagger:
    image: swaggerapi/swagger-ui
    ports:
    - ${RIBAC_SWAGGER_EXTERNAL_PORT:?RIBAC_SWAGGER_EXTERNAL_PORT}:8080
    volumes:
    - ./src/main/resources:/resources
    environment:
      SWAGGER_JSON: /resources/ribac.yaml