version: '3.7'
services:
  ribac-db:
    image: 'mysql:8.0'
    ports:
      - '${RIBAC_DB_EXTERNAL_PORT:?RIBAC_DB_EXTERNAL_PORT}:3306'
    restart: 'always'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: '${RIBAC_DB_ROOT_PASSWORD:?RIBAC_DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${RIBAC_DB_NAME:?RIBAC_DB_NAME}'
      MYSQL_USER: '${RIBAC_DB_USER:?RIBAC_DB_USER}'
      MYSQL_PASSWORD: '${RIBAC_DB_PASSWORD:?RIBAC_DB_PASSWORD}'
    volumes:
      - './ribac.sql:/docker-entrypoint-initdb.d/ribac.sql:ro'

  ribac:
    image: 'ribac:0.1.0-SNAPSHOT'
    build: '.'
    depends_on:
      - 'ribac-db'
    ports:
      - '${RIBAC_PORT:?RIBAC_PORT}:8080'
    restart: 'always'