version: '3.7'
services:
  ribac-db:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ribac'