version: '3.7'
services:
  ribac-db:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    restart: 'always'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ribac'
    volumes:
      - './ribac.sql:/docker-entrypoint-initdb.d/ribac.sql:ro'

  ribac:
    image: 'ribac:0.1.0-SNAPSHOT'
    build: '.'
    depends_on:
      - 'ribac-db'
    ports:
      - '8080:8080'
    restart: 'always'