openapi: 3.0.2

info:
  title: ribac - RIghtBasedAccessControl
  version: 0.1.0-SNAPSHOT

servers:
- url: http://localhost:8080

paths:
  /users:
    post:
      operationId: createUser
      summary: Creates a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - id
              properties:
                id:
                  type: string
                  minLength: 1
                  maxLength: 255
            example:
              id: user123
        required: true
      responses:
        201:
          description: Successfully created thes new user
          content:
            application/json:
              schema:
                type: object
                required:
                - createdUser
                properties:
                  createdUser:
                    type: object
                    required:
                    - id
                    properties:
                      id:
                        type: string
              example:
                createdUser:
                  id: user123
        409:
          description: A user already exists with the given id
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Error'
              example:
                error:
                  message: "A user already exists with the id 'user123'"

components:
  schemas:
    Error:
      type: object
      required:
      - error
      properties:
        error:
          type: object
          required:
          - message
          properties:
            message:
              type: string